import { useState } from 'react';
import { Calendar, Download, Clock } from 'lucide-react';

interface CalendarButtonProps {
  leadName: string;
  propertyAddress: string;
  leadEmail?: string;
  leadPhone?: string;
  notes?: string;
}

function generateICS(props: {
  title: string;
  description: string;
  location: string;
  startDate: Date;
  endDate: Date;
}): string {
  const pad = (n: number) => n.toString().padStart(2, '0');
  const formatDate = (d: Date) =>
    `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`;

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//WholeScale OS//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `DTSTART:${formatDate(props.startDate)}`,
    `DTEND:${formatDate(props.endDate)}`,
    `SUMMARY:${props.title}`,
    `DESCRIPTION:${props.description.replace(/\n/g, '\\n').replace(/,/g, '\\,')}`,
    `LOCATION:${props.location.replace(/,/g, '\\,')}`,
    `UID:${Date.now()}-${Math.random().toString(36).slice(2)}@wholescale.io`,
    'STATUS:CONFIRMED',
    'END:VEVENT',
    'END:VCALENDAR',
  ].join('\r\n');
}

export function CalendarButton({ leadName, propertyAddress, leadEmail, leadPhone, notes }: CalendarButtonProps) {
  const [showPicker, setShowPicker] = useState(false);
  const [selectedDate, setSelectedDate] = useState('');
  const [selectedTime, setSelectedTime] = useState('10:00');
  const [duration, setDuration] = useState(30);

  const handleDownload = () => {
    if (!selectedDate) return;

    const [year, month, day] = selectedDate.split('-').map(Number);
    const [hours, minutes] = selectedTime.split(':').map(Number);
    const start = new Date(year, month - 1, day, hours, minutes);
    const end = new Date(start.getTime() + duration * 60 * 1000);

    const description = [
      `Call with ${leadName}`,
      `Property: ${propertyAddress}`,
      leadPhone ? `Phone: ${leadPhone}` : '',
      leadEmail ? `Email: ${leadEmail}` : '',
      notes ? `\nNotes: ${notes}` : '',
      '\n--- Generated by WholeScale OS ---',
    ].filter(Boolean).join('\n');

    const icsContent = generateICS({
      title: `Call with ${leadName} - ${propertyAddress.split(',')[0]}`,
      description,
      location: propertyAddress,
      startDate: start,
      endDate: end,
    });

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `call-${leadName.toLowerCase().replace(/\s+/g, '-')}.ics`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    setShowPicker(false);
  };

  const getQuickDate = (offset: number) => {
    const d = new Date();
    d.setDate(d.getDate() + offset);
    return d.toISOString().split('T')[0];
  };

  return (
    <div className="relative">
      <button
        onClick={() => setShowPicker(!showPicker)}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border border-[var(--t-primary-border)] bg-[var(--t-primary-dim)] text-[var(--t-primary)] hover:bg-[var(--t-primary-dim-hover)] hover:border-[var(--t-primary-border-hover)] transition-colors"
      >
        <Calendar size={12} />
        Add to Calendar
      </button>

      {showPicker && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setShowPicker(false)} />
          <div className="absolute bottom-full mb-2 left-0 w-72 bg-[var(--t-surface)] border border-[var(--t-border)] rounded-xl shadow-2xl z-50 p-4">
            <h4 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
              <Calendar size={14} className="text-[var(--t-primary)]" />
              Schedule: {leadName}
            </h4>

            {/* Quick options */}
            <div className="flex gap-1.5 mb-3 flex-wrap">
              {[
                { label: 'Today', offset: 0 },
                { label: 'Tomorrow', offset: 1 },
                { label: 'In 3 days', offset: 3 },
                { label: 'Next week', offset: 7 },
              ].map(opt => (
                <button
                  key={opt.label}
                  onClick={() => setSelectedDate(getQuickDate(opt.offset))}
                  className={`px-2 py-1 text-[10px] rounded-lg border transition-colors ${
                    selectedDate === getQuickDate(opt.offset)
                      ? 'bg-[var(--t-primary-dim)] border-[var(--t-primary-border)] text-[var(--t-primary)]'
                      : 'bg-[var(--t-surface)] border-[var(--t-border)] text-[var(--t-text-muted)] hover:text-white'
                  }`}
                >
                  {opt.label}
                </button>
              ))}
            </div>

            {/* Date & Time */}
            <div className="grid grid-cols-2 gap-2 mb-3">
              <div>
                <label className="text-[10px] text-[var(--t-text-muted)] mb-1 block">Date</label>
                <input
                  type="date"
                  value={selectedDate}
                  onChange={(e) => setSelectedDate(e.target.value)}
                  className="w-full px-2 py-1.5 text-xs rounded-lg bg-[var(--t-surface-subtle)] border border-[var(--t-border)] text-white focus:outline-none focus:ring-1 focus:ring-[var(--t-primary)]"
                />
              </div>
              <div>
                <label className="text-[10px] text-[var(--t-text-muted)] mb-1 block">Time</label>
                <input
                  type="time"
                  value={selectedTime}
                  onChange={(e) => setSelectedTime(e.target.value)}
                  className="w-full px-2 py-1.5 text-xs rounded-lg bg-[var(--t-surface-subtle)] border border-[var(--t-border)] text-white focus:outline-none focus:ring-1 focus:ring-[var(--t-primary)]"
                />
              </div>
            </div>

            {/* Duration */}
            <div className="mb-3">
              <label className="text-[10px] text-[var(--t-text-muted)] mb-1 block flex items-center gap-1">
                <Clock size={9} /> Duration
              </label>
              <div className="flex gap-1.5">
                {[15, 30, 45, 60].map(d => (
                  <button
                    key={d}
                    onClick={() => setDuration(d)}
                    className={`flex-1 py-1 text-[10px] rounded-lg border transition-colors ${
                      duration === d
                        ? 'bg-[var(--t-primary-dim)] border-[var(--t-primary-border)] text-[var(--t-primary)]'
                        : 'bg-[var(--t-surface)] border-[var(--t-border)] text-[var(--t-text-muted)] hover:text-white'
                    }`}
                  >
                    {d}m
                  </button>
                ))}
              </div>
            </div>

            {/* Download */}
            <button
              onClick={handleDownload}
              disabled={!selectedDate}
              className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-[var(--t-primary)] hover:bg-[var(--t-primary-hover)] disabled:opacity-40 disabled:cursor-not-allowed text-white text-xs font-medium rounded-lg transition-colors"
            >
              <Download size={12} />
              Download .ics File
            </button>
            <p className="text-[10px] text-[var(--t-text-muted)] mt-2 text-center">
              Opens in Google Calendar, Outlook, or Apple Calendar
            </p>
          </div>
        </>
      )}
    </div>
  );
}
